apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: demo-app
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007 # from 30000 to 32767

# get minikube ip and it'll be accessible on port 30007 via http
